FLASK_APP=main
FLASK_DEBUG=True
PORT=8080
DEBUG_MODE=True
UNIVERSITY_API_URL=http://universities.hipolabs.com/search?country=

CACHE_TYPE=redis
CACHE_REDIS_HOST=redis
CACHE_REDIS_PORT=6379
CACHE_REDIS_DB=0
CACHE_REDIS_URL=redis://127.0.0.1:6379/0
CACHE_DEFAULT_TIMEOUT=1

MONGO_DB_URL=localhost
MONGO_DB_PORT=27017